version: '3.1'

services:

  db:
    container_name: db
    image: postgres
    restart: always
    env_file:
      - ./.env.db
    volumes:
      - ./db/db_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  tasks_api:
    image: rest_api
    build: ./
    command: gunicorn tasks_manager.wsgi:application --bind 0.0.0.0:8000
    restart: always
    volumes:
      - .:/rest_api
      - static_volume:/tasks_manager/static
#      - media_volume:/home/app/web/media
    env_file:
      - ./.env.pr
    expose:
      - 8000
    depends_on:
      - db
  nginx:
    build: ./nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - static_volume:/tasks_manager/static
#      - media_volume:/tasks_manager/media
    depends_on:
      - tasks_api

volumes:
  static_volume:
#  media_volume:
